# Generated by Django 3.1.4 on 2020-12-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveldata',
            options={'ordering': ['-created_at']},
        ),
    ]
